export const authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOG_OUT:"LOG_OUT"
}

export const userConstant={
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL:'USER_REGISTER_FAIL'
}